apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-pod
  namespace: books-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      # books-api container configuration
      - name: books-api
        resources:
          limits:
            cpu: "1000m"
            memory: "100M"
          requests:
            cpu: "500m"
            memory: "50M"
