apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./kind-books-config.yaml
- ../../base/books-pod/
patchesStrategicMerge:
- ./kind-books-patch.yaml
images:
- name: books-api-image
  newName: books-api-amd64
  newTag: "1.0"
