# Build go binary
FROM golang:1.17.7-alpine3.15 as build_flights-api
ENV CGO_ENABLED 0
ARG BUILD_REF

COPY . /fds

WORKDIR /fds/app/services/flights-api
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Run the go binary in alpine.
FROM alpine:3.15

ARG BUILD_DATE
ARG BUILD_REF

COPY --from=build_flights-api /fds/app/services/flights-api/flights-api /services/flights-api

WORKDIR /services

CMD ["./flights-api"]
