# Build go binary
FROM golang:1.17.7-alpine3.15 as build_flights-api
ENV CGO_ENABLED 0
ARG BUILD_REF

COPY . /fds

WORKDIR /fds
RUN go build -o flights-api -ldflags "-X main.build=${BUILD_REF}"

# Run the go binary in alpine.
FROM alpine:3.15

ARG BUILD_DATE
ARG BUILD_REF

COPY --from=build_flights-api /fds/flights-api /service/flights-api

WORKDIR /service

CMD ["./flights-api"]
