apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights-pod
  namespace: flights-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flights
  template:
    metadata:
      labels:
        app: flights
    spec:
      containers:
      # flights-api container configuration
      - name: flights-api
        resources:
          limits:
            cpu: "1000m"
            memory: "100M"
          requests:
            cpu: "500m"
            memory: "50M"
