apiVersion: v1
kind: Namespace
metadata:
  name: books-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-pod # Base POD name
  namespace: books-system
spec:
  selector:
    matchLabels:
      app: books # Selector for POD name search.
  template:
    metadata:
      labels:
        app: books
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: run-dbmigrate
          image: books-api-image
          command: ["./tools/dbmigrate"]
        - name: run-dbseed
          image: books-api-image
          command: ["./tools/dbseed"]
      containers:
        - name: books-api
          image: books-api-image
          ports:
            - name: books-api
              containerPort: 3000
            - name: books-debug
              containerPort: 4000
          resources:
            limits:
              cpu: "1000m"
              memory: "100M"
            requests:
              cpu: "500m"
              memory: "50M"
          readinessProbe: # readiness probes mark the service available to accept traffic.
            httpGet:
              path: /debug/readiness
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
            httpGet:
              path: /debug/liveness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: BOOKS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_host
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NAMESPACE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
  namespace: books-system
spec:
  type: ClusterIP
  selector:
    app: books
  ports:
    - name: books-api
      port: 3000 # refers to the port we want to access outside the cluster
      targetPort: books-api # refers to the container port inside the cluster
    - name: books-debug
      port: 4000 # refers to the port we want to access outside the cluster
      targetPort: books-debug # refers to the container port inside the cluster
