apiVersion: v1
kind: Namespace
metadata:
  name: flights-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights-pod # Base POD name
  namespace: flights-system
spec:
  selector:
    matchLabels:
      app: flights # Selector for POD name search.
  template:
    metadata:
      labels:
        app: flights 
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: flights-api
          image: flights-api-image
          ports:
            - name: flights-api
              containerPort: 3000
            - name: flights-debug
              containerPort: 4000
          resources:
            limits:
              cpu: "1000m"
              memory: "100M"
            requests:
              cpu: "500m"
              memory: "50M"
          readinessProbe: # readiness probes mark the service available to accept traffic.
            httpGet:
              path: /debug/readiness
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
            httpGet:
              path: /debug/liveness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NAMESPACE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: flights-service
  namespace: flights-system
spec:
  type: ClusterIP
  selector:
    app: flights
  ports:
    - name: flights-api
      port: 3000 # refers to the port we want to access outside the cluster
      targetPort: flights-api # refers to the container port inside the cluster
    - name: flights-debug
      port: 4000 # refers to the port we want to access outside the cluster
      targetPort: flights-debug # refers to the container port inside the cluster
