apiVersion: v1
kind: Namespace
metadata:
  name: flights-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights-pod # Base POD name
  namespace: flights-system
spec:
  selector:
    matchLabels:
      app: flights # Selector for POD name search.
  template:
    metadata:
      labels:
        app: flights 
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: flights-api
          image: flights-api-amd64:1.0
          resources:
            limits:
              cpu: "1000m"
              memory: "100M"
            requests:
              cpu: "500m"
              memory: "50M"
 